server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
spring.jpa.hibernate.ddl-auto: update

#jsoup-setting:
#  userAgent: DmitriusSearchBot
#  referrer: https://www.google.com

# example values

indexing-settings:
  sites:
    - url: https://shm.ru
      name: Исторический музей
    - url: https://www.svetlovka.ru
      name: СВЕТЛОВКА
    - url: https://snaplistings.com
      name: Snap listings
    - url: https://www.bluespark.digital
      name: Bluespark Digital LLC
    - url: https://edriver.by
      name: eDiver.by
