server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 20000
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 10000
      max-lifetime: 1000
      auto-commit: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
spring.jpa.hibernate.ddl-auto: update

#jsoup-setting:
#  userAgent: DmitriusSearchBot
#  referrer: https://www.google.com

# example values

indexing-settings:
  sites:
    - url: https://www.playback.ru
      name: PlayBack.Ru
    - url: https://bulgakovmuseum.ru
      name: Музей М.А. Булгакова
    - url: https://et-cetera.ru/mobile
      name: ET CETERA
